### PR TITLE
ST-Feature Spotify api

### PR DESCRIPTION
**Pull request by luvizzz**
- Adding Successful Login: able to generate and use accessToken
- Adding Get Artist information: GET https://api.spotify.com/v1/search?q=Red Hot Chilli Peppers&type=artist 

TODO:
- Remove Google stuff and rename classes
- Generalize endpoints used ("https://api.spotify.com")

### CODE REVIEW

**Comment by luvizzz** [comment]
@vinipx check this out! :+1:

**Review by vinipx — COMMENTED** [review]
Looks nice! 👍 
Sobre os TODOs? Vai incluir na mesma PR?

**Comment by luvizzz** [comment]
>  Sobre os TODOs? Vai incluir na mesma PR?

Done!

**Review by vinipx — APPROVED** [review]
o/

**Pull request merged**
